[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eggd-contaminant-detector"
version = "0.1.0"
description = "DNANexus app for cross-contamination detection"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Sophie Paul", email = "sophie.paul3@nhs.net" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "dxpy==0.407.0",
    "contaminant-detector @ {root:uri}/src/contaminant_detector"
]

[project.optional-dependencies]
dev = [
    "pip-audit",
    "pytest>=8.0.0",
    "black>=24.0.0",
    "mypy>=1.8.0",
    "pytest-cov",
    "pytest-mock",
    "types-docker",
    "pandas-stubs",
    "types-seaborn"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
only-include = ["scripts"]

[tool.black]
line-length = 88
target-version = ['py312']

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["src/sompy/tests", "src/contaminant_detector/tests"]
filterwarnings = [
    "ignore:Use setlocale:DeprecationWarning:pytest_nunit"
]
