[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "contaminant-detector"
version = "0.1.0"
description = "A pipeline for running sompy in Docker and analyzing the resulting stats."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Sophie Paul", email = "sophie.paul3@nhs.net" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "pip-audit",
    "pandas==3.0.1",
    "seaborn==0.13.2",
    "ambergris==0.1.0.1",
    "sompy @ {root:uri}/../sompy"
]

[project.scripts]
run-sompy-pair = "contaminant_detector:run_sompy_pair"
run-sompy-batch = "contaminant_detector:run_sompy_batch"
plot-recall = "contaminant_detector:plot_recall"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "black>=24.0.0",
    "mypy>=1.8.0",
    "pytest-mock",
    "pytest-cov",
    "types-docker",
    "pandas-stubs",
    "types-seaborn"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/contaminant_detector"]

[tool.black]
line-length = 88
target-version = ['py312']

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["contaminant_detector.*"]
follow_untyped_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore:Use setlocale:DeprecationWarning:pytest_nunit"
]
