from pathlib import Path
from typing import Callable, cast

import ambergris  # type: ignore

from . import _commands, _paths


def run_bcftools_norm(
    image: Path | str, out_dir: Path, vcf: Path, reference: Path
) -> Path:
    outpath = _run_tool(
        image=image,
        tool=_commands._bcftools_norm,
        out_dir=out_dir,
        vcf=vcf,
        reference=reference,
    )
    return outpath


def run_bcftools_sort(image: Path | str, out_dir: Path, vcf: Path) -> Path:
    outpath = _run_tool(
        image=image, tool=_commands._bcftools_sort, out_dir=out_dir, vcf=vcf
    )
    return outpath


def run_sompy(
    image: Path | str,
    out_dir: Path,
    truth: Path,
    query: Path,
    reference: Path,
    panel_regions: Path,
) -> Path:
    outpath = _run_tool(
        image=image,
        tool=_commands._sompy,
        out_dir=out_dir,
        truth=truth,
        query=query,
        reference=reference,
        panel_regions=panel_regions,
    )
    return outpath


def _run_tool(
    image: Path | str,
    tool: Callable,
    out_dir: Path,
    *tool_args: Path,
    **tool_kwargs: Path,
) -> Path:
    """
    Run a tool in a Docker image from a selection (one of ["sompy", "bcftools norm", "bcftools sort"])

    Args:
        image: The Docker image name or ID (e.g., 'bcftools:latest')
        tool: The key for the tool in TOOL_REGISTRY. Options are one of ["sompy", "bcftools norm", "bcftools sort"]
        out_dir: The host directory where output files will be written
        *tool_args: Variable length argument list passed to the tool command
        **tool_kwargs: Arbitrary keyword arguments passed to the tool command

    Returns:
        A pathlib.Path object pointing to the output generated by the tool
    """
    in_dir = _paths._resolve_in_dir(*tool_args, **tool_kwargs)
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    mounts = _paths._make_mounts(in_dir, out_dir)
    cmd, outpath = tool(mounts=[*mounts], *tool_args, **tool_kwargs)
    ambergris.run_container(image, cmd, *mounts)
    outpath = cast(Path, outpath)
    return outpath
