[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sompy"
version = "0.1.0"
description = "Functions for running sompy and bcftools in their respective docker containers, and parsing the output"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Sophie Paul", email = "sophie.paul3@nhs.net" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "ambergris==0.1.0.1"
]

[project.optional-dependencies]
dev = [
    "pip-audit",
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.15.1",
    "black>=24.0.0",
    "mypy>=1.8.0",
    "types-docker",
    "pandas-stubs",
    "types-seaborn"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/sompy"]

[tool.hatch.envs.default]
features = ["dev"]

[tool.black]
line-length = 88
target-version = ['py312']

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["ambergris.*"]
follow_untyped_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=sompy --cov-report=term-missing"
