name: Python Unit Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]" 

      - name: Run unit tests
        run: |
          pytest src/

      - name: Run type check
        run: |
          mypy scripts/
          mypy src/contaminant_detector/src/
          mypy src/sompy/src/

      - name: Run format check
        run: |
          black --check .
      
      - name: Run package security check
        run: |
          pip-audit
